baseURL = "http://example.com/"
languageCode = "en-us"
title = "Jordan"
theme = "minimal"
disqusShortname = "PaperTapes" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Jordan Weaver"
    description = "Developer. Scientist. Human."
    githubUsername = "jordanweaver"
    accent = "#dc322f"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts! (Merriweather,
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["python", "bash", "go", "haskell"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:i.jordanweaver@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/jordanweaver/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/papertapes/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/cjordanweaver/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://stackoverflow.com/users/2929330/jweaver"
    name = "stack-overflow"
    weight = 5

[[menu.icon]]
    url = "https://soundcloud.com/papertapes"
    name = "soundcloud"
    weight = 6

[[menu.icon]]
    url = "https://open.spotify.com/user/jordieweaver"
    name = "spotify"
    weight = 7
